### ISSUE TITLE
About re-scoring analysis

### ISSUE THREAD

**Issue by 07hyx06** [genforce/sefa#1]
Hi, I want to do some experiment on disentanglement, but i am confused about the metric.
Suppose G(z) is the origin image and d is the dirction, how to select k for re-scoring G(z+kd)?

**Comment by ShenYujun** [comment]
You can set `k=1` for all directions for a fair comparison.

**Comment by rainsoulsrx** [comment]
![image](https://user-images.githubusercontent.com/24955512/89015776-334dd180-d34a-11ea-9060-ac0c5f61f28b.png)
hi，In this table, you mentioned " each level of layers", for example, Middle Layers (2-5),  means 2-5 layers together as a whole matrix or a matrix for each layer? I think it must satisfy linearity, but 2-5 layers together is not linearity because there is nonlinear activation function between them.

**Comment by ShenYujun** [comment]
If you only consider how the latent code is fed into these AdaIN operations for each layer, they are linear.

**Comment by 07hyx06** [comment]
Suppose layer2's weight matrix size is [1024,512], layer3's size is [512,512], layer 4's size is [256,512]. If consider layer2~4, it firstly  concatenate them together and get a [1024+512+256,512]=[1792,512] size matrix A, and compute A^T A's eigen vector as the direction?

**Comment by ShenYujun** [comment]
@07hyx06 Yes, you are right.

**Comment by 07hyx06** [comment]
> @07hyx06 Yes, you are right.

I concatenate all of the 18 layers together and get a [10176,512] weight matrix A, and then normalized A's row by A[i]/=torch,norm(A[i]) before performing eigen decomposition, but i still cannot get the results in Table 1. The cos distance in my implement is 0.8+ for all attribute. Is it needs other tricks? I used torch.symeig to compute the eigens and the biggest eigen is 60 6.55.

**Comment by ShenYujun** [comment]
Please try `np.linalg.eig(A.T.dot(A))`
