### ISSUE TITLE
Some questions about your code

### ISSUE THREAD

**Issue by BurnWan** [genforce/sefa#5]
https://github.com/genforce/sefa/blob/c60c53665bdba2f439b8fa0b4d2411243ea499c8/utils.py#L185
In this line, I wonder why you used torch.flip to flip the weight. I think there is no need to flip the weights before implementing convolution in CNN.

**Comment by ShenYujun** [comment]
That is because we use [convolution](https://github.com/genforce/sefa/blob/c60c53665bdba2f439b8fa0b4d2411243ea499c8/models/pggan_generator.py#L100) to replace the fully-connected layer in the [official PGGAN](https://github.com/tkarras/progressive_growing_of_gans/blob/35d6c23c578bdf2be185d026c6b3d366c1518120/networks.py#L184).

**Comment by BurnWan** [comment]
> That is because we use [convolution](https://github.com/genforce/sefa/blob/c60c53665bdba2f439b8fa0b4d2411243ea499c8/models/pggan_generator.py#L100) to replace the fully-connected layer in the [official PGGAN](https://github.com/tkarras/progressive_growing_of_gans/blob/35d6c23c578bdf2be185d026c6b3d366c1518120/networks.py#L184).

I see that, I mean you use torch.conv2d(x,weight), the result should be y = x[0]w[0]+x[1]w[1]+x[2]w[2]+x[3]w[3], instead of y=x[0]w[3]+x[1]w[2]+x[2]w[1]+x[3]w[0]. In this case, it is unnecessary to use the flip function.
https://github.com/genforce/sefa/blob/c60c53665bdba2f439b8fa0b4d2411243ea499c8/models/pggan_discriminator.py#L336

**Comment by ShenYujun** [comment]
You are correct. We just want to make sure to get the same factorized results as using the official model.
